# Base image
FROM eclipse-temurin:17-jdk

# Application directory
WORKDIR /app

# Copy JAR file generated by Jenkins Maven build
COPY target/*.jar app.jar

# Expose application port
EXPOSE 9090

# Start application
ENTRYPOINT ["java", "-jar", "app.jar"]
