# Base image
FROM openjdk:17-jdk-slim

# Application directory
WORKDIR /app

# Copy JAR file generated by Jenkins Maven build
COPY target/*.jar app.jar

# Expose application port
EXPOSE 8090

# Start application
ENTRYPOINT ["java", "-jar", "app.jar"]
